export const routeManifest = {
  root: ['/auth','/payments','/transactions','/ledger','/families','/handlers','/events','/settlements','/disputes','/reports','/notifications','/addresses'],
  auth: ['POST /auth/register','POST /auth/login','POST /auth/logout','POST /auth/refresh-token','GET /auth/google','GET /auth/google/callback','POST /auth/forgot-password','POST /auth/reset-password','POST /auth/change-password','GET /auth/me','POST /auth/verify-email','POST /auth/resend-verification','POST /auth/verify-phone','POST /auth/resend-otp','POST /pin/set','POST /pin/verify','POST /pin/change','POST /pin/reset','GET /auth/sessions','DELETE /auth/sessions/:id'],
  payments: ['POST /payments','POST /payments/webhook','GET /payments','GET /payments/:id','GET /payments/my','POST /payments/:id/confirm','POST /payments/:id/fail','GET /payments/event/:eventId','GET /payments/handler/:handlerId'],
  transactions: ['POST /transactions','POST /transactions/:id/reverse','GET /transactions','GET /transactions/:id','GET /transactions/ledger/:familyId','GET /transactions/event/:eventId','GET /transactions/family/:familyId','GET /transactions/handler/:handlerId'],
  ledger: ['GET /ledger','GET /ledger/:familyId','GET /ledger/:familyId/balance','GET /ledger/:familyId/history','GET /ledger/between/:familyA/:familyB','GET /ledger/event/:eventId'],
  families: ['POST /families','PUT /families/:id','PATCH /families/:id/address','GET /families','GET /families/:id','GET /families/:id/balance','GET /families/:id/ledger','PATCH /families/:id/activate','PATCH /families/:id/deactivate','POST /families/:id/link-user','GET /families/:id/events','GET /families/:id/transactions'],
  handlers: ['POST /handlers','PATCH /handlers/:id','GET /handlers','GET /handlers/me','GET /handlers/me/commission','GET /handlers/me/families','GET /handlers/me/events','GET /handlers/:id','GET /handlers/:id/families','GET /handlers/:id/transactions','GET /handlers/:id/performance','PATCH /handlers/:id/activate','PATCH /handlers/:id/deactivate'],
  events: ['POST /events','PATCH /events/:id','POST /events/:id/participants','POST /events/:id/settlement','GET /events','GET /events/:id','GET /events/:id/participants','GET /events/:id/settlement','POST /events/:id/start','POST /events/:id/complete','POST /events/:id/archive','POST /events/:id/cancel','POST /events/:id/add-family','DELETE /events/:id/remove-family/:familyId','GET /events/:id/payments','GET /events/:id/transactions','GET /events/:id/ledger'],
  settlements: ['POST /settlements','GET /settlements','GET /settlements/:id','POST /settlements/event/:eventId','GET /settlements/event/:eventId','POST /settlements/:id/execute','POST /settlements/:id/cancel'],
  disputes: ['POST /disputes','GET /disputes','GET /disputes/:id','POST /disputes/:id/resolve','POST /disputes/:id/reject','GET /disputes/family/:familyId','GET /disputes/event/:eventId'],
  reports: ['GET /reports/summary','GET /reports/transactions','GET /reports/payments','GET /reports/event/:eventId','GET /reports/handler/:handlerId','GET /reports/family/:familyId','GET /reports/top-contributors','GET /reports/defaulters','GET /reports/collection','GET /reports/ledger-summary','GET /reports/balance-sheet'],
  notifications: ['GET /notifications','POST /notifications','PATCH /notifications/:id/read'],
  addresses: ['GET /addresses','POST /addresses','GET /addresses/:id']
} as const;
